import os
import json
from python.helpers.tool import Tool, Response


class VideoGen(Tool):
    """ViMax-style agentic video generation with storyboard planning."""

    async def execute(self, **kwargs) -> Response:
        method = self.method if hasattr(self, "method") and self.method else "from_idea"

        if method == "from_idea":
            return await self._from_idea(**kwargs)
        elif method == "from_script":
            return await self._from_script(**kwargs)
        else:
            return Response(message=f"Unknown method: {method}", break_loop=False)

    async def _from_idea(self, **kwargs) -> Response:
        idea = self.args.get("idea", "") or kwargs.get("idea", "")
        if not idea:
            return Response(
                message="Error: 'idea' parameter is required. Provide a creative idea for video generation.",
                break_loop=False,
            )

        style = self.args.get("style", "cinematic") or kwargs.get("style", "cinematic")
        duration = self.args.get("duration", "60") or kwargs.get("duration", "60")

        prompt = f"""You are a professional video director and storyboard artist. Given a creative idea, produce a detailed, structured storyboard for a {duration}-second video in a {style} style.

Creative Idea: {idea}

Generate a structured storyboard in the following JSON format:

{{
  "title": "Video title",
  "style": "{style}",
  "duration_seconds": {duration},
  "aspect_ratio": "16:9",
  "mood": "Overall mood/tone",
  "color_palette": ["#hex1", "#hex2", "#hex3", "#hex4"],
  "music_direction": "Description of music/sound design",
  "scenes": [
    {{
      "scene_number": 1,
      "duration_seconds": 5,
      "description": "Detailed visual description of the scene",
      "camera_angle": "e.g., wide shot, close-up, aerial, tracking",
      "camera_movement": "e.g., slow pan left, zoom in, static, dolly forward",
      "lighting": "Description of lighting setup",
      "text_overlay": "Any text to display (or null)",
      "transition_in": "cut/fade/dissolve/wipe",
      "transition_out": "cut/fade/dissolve/wipe",
      "visual_effects": "Any VFX or motion graphics notes",
      "audio_notes": "Sound effects or music cues for this scene"
    }}
  ],
  "narration": "Full narration script if applicable (or null)",
  "technical_notes": "Any additional production notes"
}}

Create enough scenes to fill the {duration}-second duration. Be specific and vivid in visual descriptions so each scene can be generated by an AI video model or built in Remotion.
"""

        try:
            response = await self.agent.call_utility_model(prompt)
            storyboard_text = str(response) if response else ""

            if not storyboard_text:
                return Response(message="Error: Failed to generate storyboard.", break_loop=False)

            # Save storyboard
            tmp_dir = os.path.join("tmp", "video_gen")
            os.makedirs(tmp_dir, exist_ok=True)
            storyboard_file = os.path.join(tmp_dir, "storyboard.json")
            with open(storyboard_file, "w") as f:
                f.write(storyboard_text)

            result = f"""Storyboard generated from idea and saved to: {storyboard_file}

--- Storyboard ---
{storyboard_text}

--- Next Steps ---
1. Use video_render:compose to create Remotion components for each scene
2. Use video_render:render to render the final video
3. Or feed individual scene descriptions to an external video generation API (Runway, Pika, etc.)
"""
            return Response(message=result[:4000], break_loop=False)
        except Exception as e:
            return Response(message=f"Error generating storyboard: {str(e)}"[:4000], break_loop=False)

    async def _from_script(self, **kwargs) -> Response:
        script = self.args.get("script", "") or kwargs.get("script", "")
        if not script:
            return Response(
                message="Error: 'script' parameter is required. Provide a script or screenplay text.",
                break_loop=False,
            )

        format_type = self.args.get("format", "narrative") or kwargs.get("format", "narrative")

        prompt = f"""You are a professional film director breaking down a script into production-ready scene descriptions. Analyze the following script and create a detailed scene-by-scene breakdown.

Script/Screenplay:
{script}

Format type: {format_type}

Generate a structured breakdown in the following JSON format:

{{
  "title": "Production title",
  "total_estimated_duration_seconds": 0,
  "format": "{format_type}",
  "scenes": [
    {{
      "scene_number": 1,
      "scene_heading": "INT/EXT. LOCATION - TIME",
      "duration_seconds": 0,
      "description": "Detailed visual description for video generation",
      "dialogue": "Any spoken lines in this scene (or null)",
      "camera_angles": [
        {{
          "shot_type": "e.g., establishing wide, medium, close-up, over-the-shoulder",
          "description": "What the camera sees",
          "duration_seconds": 0
        }}
      ],
      "camera_movement": "Primary camera movement for the scene",
      "lighting_setup": "Key, fill, back light description; mood lighting notes",
      "color_grading": "Warm/cool, saturated/desaturated, specific LUT reference",
      "props_and_set": "Key visual elements in the scene",
      "characters": ["List of characters present"],
      "emotion": "Dominant emotional tone",
      "sound_design": {{
        "ambient": "Background/environment sounds",
        "sfx": "Specific sound effects",
        "music": "Music cues or mood"
      }},
      "transition_to_next": "cut/fade/dissolve/match cut/smash cut",
      "vfx_notes": "Any visual effects needed (or null)",
      "gen_prompt": "A concise, optimized prompt for AI video generation models to recreate this scene"
    }}
  ],
  "cast_notes": "Character descriptions and casting direction",
  "production_notes": "Overall production guidance"
}}

Be thorough in the visual descriptions. Each scene's 'gen_prompt' should be a self-contained prompt optimized for AI video generation (Runway Gen-3, Sora, Pika, etc.) that captures the essence of the scene in under 200 words.
"""

        try:
            response = await self.agent.call_utility_model(prompt)
            breakdown_text = str(response) if response else ""

            if not breakdown_text:
                return Response(message="Error: Failed to generate scene breakdown.", break_loop=False)

            # Save breakdown
            tmp_dir = os.path.join("tmp", "video_gen")
            os.makedirs(tmp_dir, exist_ok=True)
            breakdown_file = os.path.join(tmp_dir, "scene_breakdown.json")
            with open(breakdown_file, "w") as f:
                f.write(breakdown_text)

            result = f"""Scene breakdown generated from script and saved to: {breakdown_file}

--- Scene Breakdown ---
{breakdown_text}

--- Next Steps ---
1. Use video_render:compose with individual scene descriptions to create Remotion components
2. Use each scene's 'gen_prompt' with external video generation APIs
3. Use video_render:render to compile and render the final video
4. Assemble generated clips using ffmpeg or a video editor
"""
            return Response(message=result[:4000], break_loop=False)
        except Exception as e:
            return Response(message=f"Error generating scene breakdown: {str(e)}"[:4000], break_loop=False)
